---
- debug:
    msg: Applying asdf plugins

- name: Install asdf plugins
  shell: |
    asdf install python 3.11.9
    asdf global python 3.11.9
    asdf plugin add python
    asdf plugin add direnv 0.35.0
    asdf direnv setup --shell zsh --version latest
  ignore_errors: true
  # no_log: True

- name: Symbolic link asdf config
  template:
    src: "{{ playbook_dir }}/templates/.asdfrc.j2"
    dest: "{{ lookup('env', 'HOME') }}/.asdfrc"
    owner: "{{ lookup('env', 'USER') }}"